name: pga_map
channels:
  - conda-forge
  - defaults
  - phlya
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - cartopy
  - pyproj
  - adjusttext
  - pdf2image
  - pip
  - pip:
    - pdfkit
